[package]
name = "cxgledit"
version = "0.1.0"
authors = ["cx <simon.farre.cx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "*"
gl = "*"
libc = "*"
freetype-rs = "*"
png = "*"